workflows:
  react-native-android:
    name: Cake-Android
    max_build_duration: 20
    instance_type: mac_mini_m1
    environment:
      android_signing:
        - cake
      groups:
        - cake
    scripts:
      - name: Set Environment
        script: | 
          npm run config:dev
      - name: Install npm dependencies
        script: | 
          npm install
      - name: Set Android SDK location
        script: | 
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/android/local.properties"
      - name: Build Android release
        script: | 
          cd android
          ./gradlew assembleRelease -PversionCode=$PROJECT_BUILD_NUMBER \
      - name: Installing App Center CLI tools
        script: | 
          npm install -g appcenter-cli
      - name: Publishing to App Center
        script: | 
          appcenter distribute release \
          --group "dev" \
          --file $APK_PATH \
          --release-notes 'App submission via Code Magic' \
          --app Cake-Apps/Cake-Android \
          --token $APP_CENTER_TOKEN \
          --quiet
    artifacts:
      - android/app/build/outputs/**/**/*.apk