workflows:
  cake-dev:
    name: Cake-Android-DEV
    max_build_duration: 20
    instance_type: mac_mini_m1
    environment:
      android_signing:
        - cake
      groups:
        - cake
    triggering:
      events:                       # List the events that trigger builds
        - push
        - pull_request
        - tag
      branch_patterns:              # Include or exclude watched branches
        - pattern: '*'
          include: true
          source: true
        - pattern: excluded-target
          include: false
          source: false
        - pattern: included-source
          include: true
          source: true
      tag_patterns:                 # Include or exlude watched tag labels
        - pattern: '*'
          include: true
        - pattern: excluded-tag
          include: false
        - pattern: included-tag
          include: true
      cancel_previous_builds: false  # Set to `true` to automatically cancel outdated webhook builds
    scripts:
      - name: Set Environment
        script: | 
          npm run config:dev
      - name: Install npm dependencies
        script: | 
          npm install
      - name: Set Android SDK location
        script: | 
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/android/local.properties"
      - name: Build Android release
        script: | 
          cd android
          ./gradlew assembleRelease -PversionCode=$PROJECT_BUILD_NUMBER \
      - name: Installing App Center CLI tools
        script: | 
          npm install -g appcenter-cli
      - name: Publishing to App Center
        script: | 
          appcenter distribute release \
          --group "Dev" \
          --file $APK_PATH \
          --release-notes 'App submission via Code Magic' \
          --app Cake-Apps/Cake-Android \
          --token $APP_CENTER_TOKEN \
          --quiet
    artifacts:
      - android/app/build/outputs/**/**/*.apk

  cake-prod:
    name: Cake-Android-PROD
    max_build_duration: 20
    instance_type: mac_mini_m1
    environment:
      android_signing:
        - cake
      groups:
        - cake
    triggering:
      events:
        - push
        - pull_request
        - tag
      branch_patterns:
        - pattern: '*master*'
          include: true
          source: true
      cancel_previous_builds: true
    scripts:
      - name: Set Environment
        script: | 
          npm run config:prod
      - name: Install npm dependencies
        script: | 
          npm install
      - name: Set Android SDK location
        script: | 
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/android/local.properties"
      - name: Build Android release
        script: | 
          cd android
          ./gradlew assembleRelease -PversionCode=$PROJECT_BUILD_NUMBER \
      - name: Installing App Center CLI tools
        script: | 
          npm install -g appcenter-cli
      - name: Publishing to App Center
        script: | 
          appcenter distribute release \
          --group "Prod" \
          --file $APK_PATH \
          --release-notes 'App submission via Code Magic' \
          --app Cake-Apps/Cake-Android \
          --token $APP_CENTER_TOKEN \
          --quiet
    artifacts:
      - android/app/build/outputs/**/**/*.apk