export const SET_ACCOUNT = 'SET_ACCOUNT';
export const RESET_ACCOUNT = 'RESET_ACCOUNT';
export const SET_TRANSACTION = 'SET_TRANSACTION';

export const SET_TRANSACTION_BACKUP = 'SET_TRANSACTION_BACKUP';
export const SET_ACCOUNT_BACKUP = 'SET_ACCOUNT_BACKUP';
